### ISSUE TITLE
Repository pattern

### ISSUE THREAD

**Issue by BobMali** [theweekendgeek/jambot#17]
I think we should use the repository pattern to decouple laravels eloquent orm from the app. 
For convenience we should think about creating an artisan-command to automate the creation of repositories.

**Comment by theweekendgeek** [comment]
Yes, this sounds very reasonable. I'll create an issue for the artisan command.

**Comment by theweekendgeek** [comment]
will we create an repository folder inside of app for repositories?

**Comment by BobMali** [comment]
That was the idea. The artisan command will create the folder if it does not exist.

**Comment by theweekendgeek** [comment]
Ok great. I will close this, as we have this covered in #18 so far
