### ISSUE TITLE
Design Document(ation)

### ISSUE THREAD

**Issue by theweekendgeek** [theweekendgeek/jambot#19]
I'm thinking about having some kind of design document(ation), a place to store decisions, UML-diagrams etc.?
The github wiki could be a possibility.

**Comment by BobMali** [comment]
The github wiki sounds like the best idea. This way all project-related information is in one spot.

**Comment by theweekendgeek** [comment]
Awesome, I will try to get that started

**Comment by theweekendgeek** [comment]
As i've started the wiki, I'll close this. Feel free to edit and reorder the wiki as needed. The pages at the moment are merely a starting point.
