### ISSUE TITLE
Interface location

### ISSUE THREAD

**Issue by BobMali** [theweekendgeek/jambot#21]
As we will propably use a lot of interfaces, we should agree on a location to store the interfaces in. How about a "Contracts"-folder in the app-folder? Normal PSR-4 namespacing would apply within the interface-folder.

**Comment by theweekendgeek** [comment]
I'm unsure about this, as I usually do not have a convention, habit or overview of best practices, when it comes to interface placement. 

If there is something that works well with PHP-namespaces, then it seems reasonable to use it.
We might face a similar question regarding our interfaces written in TypeScript.

**Comment by BobMali** [comment]
As i said i am a fan of using the contracts-folder solution with interfaces in their own folder-structure/namespaces. The other solution would be to store the interfaces next to the implementing files which is fine to. The first solution seems more orderly to me though.

**Comment by theweekendgeek** [comment]
the other is what i usually did, but it the first solution seems like a good idea then.

**Comment by theweekendgeek** [comment]
I'll move this into the backlog

**Comment by theweekendgeek** [comment]
Update: I'll actually close this now, so it does not block the artisan issue
