### ISSUE TITLE
Code Quality Services

### ISSUE THREAD

**Issue by theweekendgeek** [theweekendgeek/jambot#5]
I would definitely like services that integrate into github somehow

Possible Services
https://github.com/marketplace/codacy - PHP + TypeScript

https://github.com/marketplace/codebeat - TypeScript, no PHP

https://github.com/marketplace/better-code-hub - more general "Clean Code" principles - PHP + TypeScript

**Comment by BobMali** [comment]
Agreed. Static code analysis is needed. 
I would suggest to omit codebeat because another tool would be needed for PHP. Codacy seems to be the best option as far as i can tell, but i am open to using Codacy and Better-Code-hub in union.

**Comment by theweekendgeek** [comment]
then we will test codacy and Better-Code-hub
