### ISSUE TITLE
CodeStyle

### ISSUE THREAD

**Issue by theweekendgeek** [theweekendgeek/jambot#6]
Decide on CodeStyles for 

- PHP
- TypeScript

**Comment by BobMali** [comment]
I suggest the normal [PSR-2](http://www.php-fig.org/psr/psr-2/) coding standard for PHP.

**Comment by BobMali** [comment]
As discussed i suggest we use the standard tslint.json provided by the Angular CLI. Furthermore i suggest following the [Angular Style Guide](https://angular.io/guide/styleguide) since we use Angular.

**Comment by theweekendgeek** [comment]
I will close this issue and create a new one which we can then use to configure the linters/config files correctly.
