### ISSUE TITLE
Docker!?

### ISSUE THREAD

**Issue by theweekendgeek** [theweekendgeek/jambot#9]
If and how to handle Docker

**Comment by theweekendgeek** [comment]
i will probably use docker for Laravel development, so we might need a place for the container config!? somewhere as part of the repo

**Comment by BobMali** [comment]
I would suggest to place the docker config in a folder in the root directory. Next to the folder for the api and the folder for the frontend-app.

**Comment by theweekendgeek** [comment]
Sounds good! I will do that.
